//
// Created by vhund on 25.03.2019.
//

#ifndef UNIVERSITY_DATA_ORGANISATION_AND_STUCTURES_LAB2_1_H
#define UNIVERSITY_DATA_ORGANISATION_AND_STUCTURES_LAB2_1_H



#endif //UNIVERSITY_DATA_ORGANISATION_AND_STUCTURES_LAB2_1_H
