//
// Created by vhund on 13.04.2019.
//

#ifndef UNIVERSITY_DATA_ORGANISATION_AND_STUCTURES_R_GRAPH_H
#define UNIVERSITY_DATA_ORGANISATION_AND_STUCTURES_R_GRAPH_H


class R_Graph {

};


#endif //UNIVERSITY_DATA_ORGANISATION_AND_STUCTURES_R_GRAPH_H
